// Draft scene-based captions. Capture dates, locations and camera settings are unconfirmed.
const originals = [
  {slug:"golden-street",title:"The street looked up.",category:"After dark",caption:"A ceiling of golden cubes. Below it, the street carries on.",alt:"Glowing cube decorations over a dark street, with a headlight below.",story:"Repeating shapes pull the eye down the lane. A single headlight brings it back to street level. Most of the scene stays in shadow; the light does the talking."},
  {slug:"red-entrance",title:"An entrance in red.",category:"Celebrations",caption:"Red, gold, and people passing through. Some entrances deserve a pause.",alt:"Red and gold decorated entrance with Jagannath imagery and people walking past.",story:"The tall facade fills the frame, but the people at its base give it scale. Open gates and warm light draw the eye inside."},
  {slug:"overhead-stars",title:"Borrowed stars.",category:"After dark",caption:"Strings of light stretching further than the eye can follow.",alt:"Strings of warm lights and star-shaped decorations across the night sky.",story:"The frame tilts upward into rows of tiny lights. Their repetition makes a canopy out of the dark."},
  {slug:"blue-canopy",title:"A different kind of blue.",category:"Details",caption:"Just light, texture, and a reason to look up.",alt:"Hanging white decorations illuminated by cyan light strips.",story:"Without the wider scene, hanging strands and bright lines become the whole subject. Cool light changes how these simple materials feel."},
  {slug:"under-blue",title:"Under the blue canopy.",category:"Celebrations",caption:"A bright canopy overhead. A moment of attention beneath it.",alt:"Visitors facing a Durga display beneath a bright blue canopy.",story:"The ceiling fills the upper frame, with the display and visitors below. The wider view brings the decoration back into its setting: a space people are sharing."},
];
const titles = ["Golden Geometry", "Scarlet Entrance", "Borrowed Stars", "Electric Blue", "Quiet Devotion"];
const captions = ["Golden cubes above a street that never stops.", "Red and gold, with the gates wide open.", "A little sky, made of lights.", "Looking up was enough.", "A moment of stillness under blue light."];
export const photoPosts = originals.map((photo, index) => ({ ...photo, title: titles[index], caption: captions[index] }));
